version: "3.4"

services:
  client:
    image: shortpoet/vite
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    env_file:
      ./.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: bash -c "npm i && npm run dev"